### PR TITLE
Prepare release 2.3.0

### PR DESCRIPTION
**Pull request by msumit**
Auto-generated client code from Apache Airflow 2.3.3 release.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
All 2000 lines +/- look good ;)

**Comment by potiuk** [comment]
BTW. Maybe unrelated, but do want to change the API version in Airlfow? It still shows 1.0.0 when you go Swagger UI ?

**Comment by msumit** [comment]
> BTW. Maybe unrelated, but do want to change the API version in Airlfow? It still shows 1.0.0 when you go Swagger UI ?

Sure, let me check that.

**Comment by msumit** [comment]
> > BTW. Maybe unrelated, but do want to change the API version in Airlfow? It still shows 1.0.0 when you go Swagger UI ?
> 
> Sure, let me check that.

Will update the version in main Airflow repo.

**Pull request merged**
