### PR TITLE
Client version 2.5.0

### PR DESCRIPTION
**Pull request by pierrejeambrun**
Just to update the source code. This will be our base for generating 2.5.0rc1

### CODE REVIEW

**Review by ephraimbuddy — APPROVED** [review]

**Review by msumit — APPROVED** [review]
lgtm

**Review by potiuk — APPROVED** [review]
Same as in "go" client. We have no "real" way to verify this is all automatically generated and while we can trust pierre as a committer, I **think** we should not store this code in the repo, but we should generate it dynamically as part of release process - so that we approve "process of generating it" rather than "code that is generated". 

But that can be done later as a follow-up if others will also agree.

**Comment by msumit** [comment]
@potiuk I like the idea of just generating the code as part of the Airflow release itself. However, I'm wondering if being an Apache project we've to keep the raw code somewhere? Yes, we can always push the code to a repo during the code generation, but will it break Apache's standard procedure of code review and release process of the client afterward?

**Comment by potiuk** [comment]
> @potiuk I like the idea of just generating the code as part of the Airflow release itself. However, I'm wondering if being an Apache project we've to keep the raw code somewhere? Yes, we can always push the code to a repo during the code generation, but will it break Apache's standard procedure of code review and release process of the client afterward?

This is a very good question and I am thinking about opening a JIRA ticket to legal team of the ASF to clarify the approach here. Technically speaking the ASF cares only (and vote is only on) the .tar.gz source code released. Everything else we release - if this can be generated using this single .tar.gz is at most "convenience package" (including for example .whl packages we release in PyPI). So as long as the code is auto-generated, we do not have have a repository for it. We **migh** want to have it for convenience though (as long as it is) auto-generated, I think and it is not ASF's concern how we release the convenience packages. I will write a message about it proposing options.

**Pull request merged**
