### PR TITLE
The sanitize_for_serialization(cls, obj) function outputs an incorret time format

### PR DESCRIPTION
**Pull request by junqilv**
Change obj.isoformat() used by the sanitize_for_serialization(cls, obj) function to process datetime type data to obj.strftime("%Y-%m-%dT%H:%M:%SZ"). In this way, the logical_date format of the body in the post request will be correct.

### CODE REVIEW

**Comment by potiuk** [comment]
Could you please explain (in commit message ideally as well) what was the problem it solves ? I don't see why it was wrong b) it would require to have test  added.

**Comment by junqilv** [comment]
> Could you please explain (in commit message ideally as well) what was the problem it solves ? I don't see why it was wrong b) it would require to have test added.

When I use airflow-client to trigger a dagrun, if I pass a logical_date argument to the DAGRun function, the following error will occur. The reason is that the sanitize_for_serialization(cls, obj) function simply converts a datetime type data into a character time.
image

**Comment by pierrejeambrun** [comment]
Hello,


Can you try with a timezone aware datetime in the client? (For instance datetime.utcnow())

**Comment by junqilv** [comment]
> Hello,
> 
> Can you try with a timezone aware datetime in the client? (For instance datetime.utcnow())
Thank for your attention to this pull request.
This has nothing to do with time zones. The difference between using datetime.utcnow() and datetime.now() will not change the format of the parameter logical_date
image

**Comment by junqilv** [comment]
My test steps are as follows:
First, when I tried to pass data in datetime format to logical_date, I found that the http request returned showed that the format of logical_date was incorrect.
image

The logical_date displayed in the Stable REST API is "logical_date": "2019-08-24T14:15:22Z", that is, ("%Y-%m-%dT%H:%M:%SZ") format.
image

So I tried to use logical_date = "2019-08-24T14:15:22Z" directly, which is a parameter in the string format that meets the rest api requirements, but the function directly threw an exception, as shown in the figure,
Then I found that airflow-client limits the type of logical_date to [datetime, none_type].
image

So I am stuck in a loop. If I pass in data in datetime format, the function sanitize_for_serialization will convert it into a string that does not conform to the stable REST API format, causing the request to fail. If a string such as logical_date = "2019-08-24T14:15:22Z" is passed in, the type check of the function parameters will fail.
So I think there are two approaches that can be taken. The first is to change the way the function sanitize_for_serialization handles logical_date, and the second is to allow strings like "2019-08-24T14:15:22Z" to be passed in to logical_date. The first method is the simplest because it only requires modifying one line of code.

**Comment by pierrejeambrun** [comment]
Cf https://github.com/apache/airflow-client-python/issues/98#issuecomment-1793521855 comments, closing, feel free to re-open if needed.

(The API requires a TZ aware datetime)

**Pull request closed without merging**
