### PR TITLE
Rebuild with airflow 2.4.2

### PR DESCRIPTION
**Pull request by csm10495**
I'm not really sure the right way to do this but this is a rebuild of this library based off the code of the recently released Airflow 2.4.2. It would be really cool if on each airflow release this got rebuilt and released up to pypi. How do releases normally work?

I basically got airflow cloned down next to airflow-client-python. Checked out 2.4.2 of airflow. Checked out the latest for airflow-client-python. Went in airflow's v1.yaml file, ensured we had:

```
security:
  - Basic: []
  - GoogleOpenId: []
  - Kerberos: []
```

Then i went to the airflow-client-python directory and ran: 

```
./clients/gen/python.sh airflow/api_connexion/openapi/v1.yaml ../airflow-client-python/airflow_client
```

added the changes via git then ran:

```
pre-commit run --all-files
```

added those changes and made this commit / PR here.

### CODE REVIEW

**Comment by potiuk** [comment]
I believe this is correct way of doing it. And possibly @msumit can shed some light on the release process here :).

**Comment by csm10495** [comment]
@msumit / @potiuk , any chance for some guidance or a merge here? 

2.4.3 is coming soon... after that it would be nice to do this again for 2.4.3 :)

**Comment by msumit** [comment]
@csm10495 overall looks ok, but we'll also need to update the version in `setup.py` file (plz document this piece as well :) ).. Another imp point to note that for client we take only Airflow's major & minor version and patch version is internal to client itself.. So for example all Airflow releases for 2.4.X would have the same client version 2.4.0, as we assume that there won't be any new API going to be added in a Airflow patch release. So in short, we won't be release another client version until Airlfow 2.5.X is out.

**Comment by msumit** [comment]
And once this PR gets merged, just follow the release process documented [here](https://github.com/apache/airflow-client-python/blob/master/dev/README_RELEASE_CLIENT.md).

**Comment by csm10495** [comment]
@msumit I'm not sure the .X for patch version is really valid though since there could be bugfixes, etc that get into airflow that we may want ported over to clients. I'll update README.md to match what you've said since that is defacto the case for now. Related chatter: https://github.com/apache/airflow/discussions/27670

**Comment by csm10495** [comment]
Done. @msumit check again. Even after merge i don't have permissions to do the release part.

**Review by msumit — APPROVED** [review]

**Comment by msumit** [comment]
@csm10495 I've merged the PR, For release, you would need access to svn repo etc, I hope @potiuk can help you to get those (not sure though).

**Pull request merged**
