### PR TITLE
Add Client Version 2.7.0

### PR DESCRIPTION
**Pull request by ephraimbuddy**

### CODE REVIEW

**Comment by potiuk** [comment]
SMth wrong: `import client` where previously `import airflow_client` ?  I guess some command line flag in the generator changed and it stopped generating the same "airflow_client" package.

**Comment by ephraimbuddy** [comment]
> SMth wrong: `import client` where previously `import airflow_client` ? I guess some command line flag in the generator changed and it stopped generating the same "airflow_client" package.

Yes. The sed command failed but I didn't look well:
`+ find /Users/ephraimbuddy/projects/airflow-client-python/airflow_client/test -type f -name '*.py' -exec sed -i '' -e s/client/airflow_client.client/g '{}' +
sed: can't read : No such file or directory`

**Comment by ephraimbuddy** [comment]
> > SMth wrong: `import client` where previously `import airflow_client` ? I guess some command line flag in the generator changed and it stopped generating the same "airflow_client" package.
> 
> Yes. The sed command failed but I didn't look well: `+ find /Users/ephraimbuddy/projects/airflow-client-python/airflow_client/test -type f -name '*.py' -exec sed -i '' -e s/client/airflow_client.client/g '{}' + sed: can't read : No such file or directory`

To fix this, I had to uninstall gnu-sed which I installed sometime in the past

**Comment by potiuk** [comment]
> > > SMth wrong: `import client` where previously `import airflow_client` ? I guess some command line flag in the generator changed and it stopped generating the same "airflow_client" package.
> > 
> > 
> > Yes. The sed command failed but I didn't look well: `+ find /Users/ephraimbuddy/projects/airflow-client-python/airflow_client/test -type f -name '*.py' -exec sed -i '' -e s/client/airflow_client.client/g '{}' + sed: can't read : No such file or directory`
> 
> To fix this, I had to uninstall gnu-sed which I installed sometime in the past

calls for an improvement in the chain :) . It's a bit strange we are using `sed` to correct those imports :exploding_head:

**Review by potiuk — APPROVED** [review]

**Pull request merged**
